### ISSUE TITLE
Display search result is missing: No results were found

### ISSUE THREAD

**Issue by hmkay** [liqd/digitalstrategie#202] opened 2021-12-15 15:22 UTC
**URL:** https://digitalstrategie-dev.liqd.net/search/?q=what
**user:** participant
**expected behaviour:** There is a short note saying if there are no results found
**behaviour:** There is no information
**important screensize:** Desktop
**device & browser:** MacOS, Firefox
**Comment/Question:** Maybe this will be solved as soon as we have their styling? Also, this was not part of the acceptance criteria

<img width="1405" alt="Bildschirmfoto 2021-12-15 um 16 21 33" src="https://user-images.githubusercontent.com/30862422/146213931-57aa3f98-0cc3-4289-b096-b20385dd4f0a.png">

**Comment by phillimorland** [comment] 2021-12-16 10:12
if it's not part of the AC then it's not a sprint issue but we can leave it in and see what happens when we have styling

**Comment by Rineee** [comment] 2021-12-16 15:55
This is a duplicate of #199, so will close

**Closed by Rineee** 2021-12-16 15:55 UTC
